#!/bin/env/python3
import rospy
from rostak.rostak_client import RosTakClient

if __name__ == "__main__":
    client = RosTakClient()
    rate = rospy.Rate(1)
    while not rospy.is_shutdown():
        client.publish_status()
        rate.sleep()
